language: ruby
rvm:
  - 2.3.0
sudo: false
cache: bundler
env:
  matrix:
    - SOLIDUS_BRANCH=master
    - SOLIDUS_BRANCH=v2.0
    - SOLIDUS_BRANCH=v1.4
    - SOLIDUS_BRANCH=v1.3
    - SOLIDUS_BRANCH=v1.2
    - SOLIDUS_BRANCH=v1.1
before_script:
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
